# Generated by Django 2.1.1 on 2018-12-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='last_scrap',
            field=models.DateTimeField(null=True),
        ),
    ]
