# Generated by Django 2.1.1 on 2018-12-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_scraper_last_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='allow_private',
            field=models.BooleanField(default=False),
        ),
    ]
