# Generated by Django 2.1.4 on 2018-12-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scraper_allow_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='pool',
            field=models.CharField(choices=[('pub', 'Public'), ('priv', 'Private'), ('wait', 'Waiting')], default='wait', max_length=4),
        ),
    ]
