# Generated by Django 2.1.4 on 2018-12-26 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181219_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipconnectionmodel',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainModel'),
        ),
    ]
