# Generated by Django 2.1.4 on 2019-01-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181226_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
