# Generated by Django 2.1.4 on 2019-01-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190104_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapmodel',
            name='url_value',
            field=models.CharField(max_length=1000),
        ),
    ]
