from .url_serializers import UrlSerializer, ConfigurationSerializer, UrlInfoSerializer
from .device_serializers import DeviceSerializer, DeviceStatisticSerializer
from .scrap_serializers import ScrapSerializer
from .domain_serializers import DomainSerializer
